platform :ios, '8.0'
inhibit_all_warnings!
target 'Chat' do
   pod 'MJRefresh'
   pod 'TimeOutHandle'
   pod 'CoreDataTools',:git => 'https://github.com/FlameGrace/CoreDataTools.git'
   pod 'OggSpeex',:git => 'https://github.com/FlameGrace/OggSpeex.git'
end

post_install do |installer|
   installer.pods_project.targets.each do |target|
	target.build_configurations.each do |config|
		if config.name == 'Debug' || config.name == 'Release'
			config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] = ''
		end
	end
    end
end
